# Generated by Django 6.0.5 on 2026-05-29 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('presupuesto', 'Presupuesto'), ('anuncio', 'Anuncio'), ('invitacion', 'Invitación')], max_length=20)),
                ('referencia_id', models.UUIDField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
    ]
