# Generated by Django 6.0.5 on 2026-06-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('presupuesto', 'Presupuesto'), ('anuncio', 'Anuncio'), ('invitacion', 'Invitación'), ('gasto_compartido', 'Gasto compartido')], max_length=20),
        ),
    ]
