# Generated by Django 6.0.5 on 2026-05-29 23:13

import apps.documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('archivo', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('tipo_archivo', models.CharField(max_length=10)),
                ('tamano_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
    ]
