# Generated by Django 6.0.5 on 2026-06-02 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='groups.grupo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conceptos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, default='')),
                ('monto', models.PositiveIntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finances.concepto')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='groups.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='GastoCompartido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_pendiente', models.PositiveIntegerField()),
                ('pagado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_compartidos', to='groups.grupo')),
                ('usuario_acreedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_acreedor', to=settings.AUTH_USER_MODEL)),
                ('usuario_deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_deudor', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos', to='finances.movimiento')),
            ],
            options={
                'db_table': 'gastos_compartidos',
            },
        ),
        migrations.CreateModel(
            name='RegistroPresupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=10)),
                ('periodicidad', models.CharField(choices=[('Puntual', 'Puntual'), ('Mensual', 'Mensual'), ('Anual', 'Anual')], default='Puntual', max_length=10)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, default='')),
                ('monto', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='finances.concepto')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='groups.grupo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presupuesto',
            },
        ),
        migrations.CreateModel(
            name='DivisionPresupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisiones_presupuesto', to='groups.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisiones_presupuesto', to=settings.AUTH_USER_MODEL)),
                ('registro_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisiones', to='finances.registropresupuesto')),
            ],
            options={
                'db_table': 'divisiones_presupuesto',
            },
        ),
        migrations.CreateModel(
            name='ReplicaGrupal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='groups.grupo')),
                ('movimiento_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_replica', to='finances.movimiento')),
                ('movimiento_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='finances.movimiento')),
            ],
            options={
                'db_table': 'replicas_grupales',
            },
        ),
        migrations.AddIndex(
            model_name='concepto',
            index=models.Index(fields=['usuario', 'tipo'], name='idx_concepto_usuario_tipo'),
        ),
        migrations.AddConstraint(
            model_name='concepto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grupo__isnull', True), ('usuario__isnull', False)), models.Q(('grupo__isnull', False), ('usuario__isnull', True)), _connector='OR'), name='concepto_contexto_exclusivo'),
        ),
        migrations.AddConstraint(
            model_name='concepto',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('grupo__isnull', True)), fields=('nombre', 'usuario'), name='concepto_nombre_usuario_personal_unique'),
        ),
        migrations.AddConstraint(
            model_name='concepto',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('usuario__isnull', True)), fields=('nombre', 'grupo'), name='concepto_nombre_grupo_unique'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='idx_mov_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['grupo', '-fecha_hora'], name='idx_mov_grupo_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['usuario', 'tipo'], name='idx_mov_usuario_tipo'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['grupo', 'tipo'], name='idx_mov_grupo_tipo'),
        ),
        migrations.AddConstraint(
            model_name='registropresupuesto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grupo__isnull', True), ('usuario__isnull', False)), models.Q(('grupo__isnull', False), ('usuario__isnull', True)), _connector='OR'), name='presupuesto_contexto_exclusivo'),
        ),
        migrations.AddIndex(
            model_name='divisionpresupuesto',
            index=models.Index(fields=['registro_presupuesto'], name='idx_division_presupuesto'),
        ),
        migrations.AddIndex(
            model_name='divisionpresupuesto',
            index=models.Index(fields=['usuario', 'grupo'], name='idx_division_usuario_grupo'),
        ),
        migrations.AlterUniqueTogether(
            name='divisionpresupuesto',
            unique_together={('registro_presupuesto', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='replicagrupal',
            unique_together={('movimiento_personal', 'grupo')},
        ),
    ]
