# Generated by Django 6.0.5 on 2026-05-29 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conceptos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, default='')),
                ('monto', models.PositiveIntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='RegistroPresupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, default='')),
                ('monto', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'presupuesto',
            },
        ),
    ]
