# Generated by Django 6.0.5 on 2026-05-29 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0002_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registropresupuesto',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='finances.concepto'),
        ),
        migrations.AddField(
            model_name='registropresupuesto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='groups.grupo'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['grupo', '-fecha_hora'], name='movimientos_grupo_i_a84bed_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['grupo', 'tipo'], name='movimientos_grupo_i_c82eaa_idx'),
        ),
    ]
