# Generated by Django 6.0.5 on 2026-06-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_gastocompartido'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='concepto',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('nombre', 'grupo'), name='conceptos_nombre_grupo_activo_unique'),
        ),
    ]
