# Generated by Django 6.0.5 on 2026-06-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_conceptos_nombre_activo_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropresupuesto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
